[package]
name = "rust-idioms"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.3"

[[bench]]
name = "simple_bench"
path = "src/rust_lang/simple_bench.rs"
harness = false